#    Copyright (C) 2024  Pranav Verma

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.

#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#    See a more apt description in LICENSE File Attached to the root of this
#    project.

name: pranavs-portfolio
version: '3'
services:
  web:
    image: ghcr.io/pranavverma-droid/portfolio:latest
    container_name: pranavs-portfolio
    ports:
      - "${PORT}:8080"
    restart: always