name: Test Docker Build (PR)

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test-blogs-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test build the Blogs Docker image
      run: |
        cd blogs
        docker build . --tag ghcr.io/pranavverma-droid/portfolio-blogs:test

  test-portfolio-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test build the Main Portfolio Docker image
      run: |
        cd main
        docker build . --tag ghcr.io/pranavverma-droid/portfolio-main:test
